[package]
name = "using-x25519-dalek"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
log = "0.4.17"
pretty_env_logger = "0.4.0"
rand_os = "0.2.2"
x25519-dalek = "1.2.0"
